training:
  train_dataset_path: path/to/train/dataset # str
  validation_dataset_path: path/to/validation/dataset # str  ## optional if not given will not validate model.
  pre_trained_weight: ""
  learning_rate : 0.001
  batch_size: 64 # int
  device: "cuda:0" # str ## cuda:0, cuda:1 or cpu
  number_of_epochs: 100 # int
  model_save_path: path/to/save/directory # str
  save_frequency: 5 # int
  enable_augmentations: True # bool

inference:
   test_dataset_path: path/to/test/dataset # str
   pre_trained_weights: path/to/trained/dnet/model # str
   device: "cuda:0" # str ## cuda:0, cuda:1 or cpu